name: CI

on:
    push:

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    java-version: '17'
                    distribution: 'adopt'

            -   name: Cache local Maven repository
                uses: actions/cache@v2
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-

            -   name: Maven Build and Sonar Checks
                run: mvn -B package appengine:deploy -Pproduction
