name: CI

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/1007291544300/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github@vaadin-and-jooq.iam.gserviceaccount.com'

      - name: Maven Build and AppEngine Deploy
        run: mvn -B package appengine:deploy -Pproduction
